version: "3.9"

services:
  frontend-dev:
    container_name: frontend-react-dev
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend
      - /frontend/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    profiles: ["dev"]

  frontend-prod:
    container_name: frontend-react-prod
    build:
      context: .
      target: production
    ports:
      - "80:80"
    profiles: ["prod"]
